Update aayu.yml

diff --git a/.github/workflows/aayu.yml b/.github/workflows/aayu.yml
--- a/.github/workflows/aayu.yml
+++ b/.github/workflows/aayu.yml
@@ -11,6 +11,7 @@ on:
       working_directory:
         description: "Terraform folder path"
         required: true
+        default: "."
 
 permissions:
   id-token: write
@@ -69,7 +70,7 @@ jobs:
         run: |
           echo "art_name=tf-plan-${{ github.event.inputs.target_env }}-${{ github.run_id }}" >> $env:GITHUB_OUTPUT
 
-      - name: Terraform Init
+      - name: Terraform Init & Validate
         shell: powershell
         working-directory: ${{ github.event.inputs.working_directory }}
         run: |
@@ -78,21 +79,33 @@ jobs:
             -backend-config="key=${{ github.event.inputs.target_env }}.terraform.tfstate" `
             -reconfigure `
             -input=false
+          terraform validate
 
      
-      - name: Create tfvars file
+      - name: Create and Verify tfvars
         shell: powershell
         working-directory: ${{ github.event.inputs.working_directory }}
         run: |
-          @"
+          Write-Host "Generating terraform.tfvars file..."
+          $content = @"
           main_subscription_id    = "${{ secrets.ARM_SUBSCRIPTION_ID }}"
           storage_subscription_id = "${{ secrets.AZURE_STORAGE_SUBSCRIPTION_ID }}"
-          "@ | Out-File -FilePath "terraform.tfvars" -Encoding utf8
+          "@
+          $content | Out-File -FilePath "terraform.tfvars" -Encoding utf8
+          
+          if (Test-Path "terraform.tfvars") {
+              Write-Host " tfvars file created successfully."
+              Get-Item "terraform.tfvars" | Select-Object Name, Length
+          } else {
+              Write-Error " Failed to create tfvars file!"
+              exit 1
+          }
 
       - name: Terraform Plan
         shell: powershell
         working-directory: ${{ github.event.inputs.working_directory }}
         run: |
+         
           terraform plan -out="tfplan.binary" -input=false
           terraform show -no-color "tfplan.binary" > plan_preview.txt
           Get-Content plan_preview.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
@@ -141,17 +154,16 @@ jobs:
         shell: powershell
         working-directory: ${{ github.event.inputs.working_directory }}
         run: |
-          if (Test-Path "tfplan.binary") {
-            terraform apply -auto-approve "tfplan.binary"
+          if (Test-Path "tfplan.binary") {        
+            terraform apply -auto-approve -input=false "tfplan.binary"
           } else {
             Write-Error "Plan file 'tfplan.binary' not found!"
             exit 1
           }
 
-      
       - name: Cleanup tfvars
         if: always()
         shell: powershell
         working-directory: ${{ github.event.inputs.working_directory }}
         run: |
-          if (Test-Path "terraform.tfvars") { Remove-Item "terraform.tfvars" }
+          if (Test-Path "terraform.tfvars") { Remove-Item "terraform.tfvars" -Force }
